### ISSUE TITLE
Error parsing task

### ISSUE THREAD

**Issue by joakim1999** [JetBrains/youtrack.mylyn.connector#10]
java.lang.NullPointerException
	at com.jetbrains.mylyn.yt.core.YouTrackTaskDataHandler.parseIssue(YouTrackTaskDataHandler.java:405)
	at com.jetbrains.mylyn.yt.core.YouTrackTaskDataHandler.readTaskData(YouTrackTaskDataHandler.java:257)
	at com.jetbrains.mylyn.yt.core.YouTrackRepositoryConnector$1.run(YouTrackRepositoryConnector.java:244)
	at com.jetbrains.youtrack.javarest.utils.MyRunnable.execute(MyRunnable.java:16)
	at com.jetbrains.mylyn.yt.core.YouTrackRepositoryConnector.performQuery(YouTrackRepositoryConnector.java:248)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:312)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:269)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:201)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by joakim1999** [comment]
Was fixed by doing an extra restart of eclipse
