### ISSUE TITLE
A message body reader for Java class com.jetbrains.youtrack.javarest.client.YouTrackIssue, and Java type class com.jetbrains.youtrack.javarest.client.YouTrackIssue, and MIME media type application/xml; charset=UTF-8 was not found

### ISSUE THREAD

**Issue by catonymous** [JetBrains/youtrack.mylyn.connector#14]
After upgrading Eclipse JEE up to 2019-06 (4.12.0) I can't synchronize the queries nor create new ones.

Environment:

>YouTrack Java REST	1.0.0.201402211229
eclipse.buildId=4.12.0.I20190605-1800
java.version=12.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=ru_RU

Stack traces:

> com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.jetbrains.youtrack.javarest.client.YouTrackIssue, and Java type class com.jetbrains.youtrack.javarest.client.YouTrackIssue, and MIME media type application/xml; charset=UTF-8 was not found
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:550)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:506)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:684)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)
	at com.jetbrains.youtrack.javarest.client.YouTrackClient.getIssue(YouTrackClient.java:95)
	at com.jetbrains.youtrack.javarest.client.YouTrackClient.getIssue(YouTrackClient.java:85)
	at com.jetbrains.mylyn.yt.core.YouTrackRepositoryConnector.getTaskData(YouTrackRepositoryConnector.java:177)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeTasksJob.synchronizeTask(SynchronizeTasksJob.java:245)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeTasksJob.runInternal(SynchronizeTasksJob.java:218)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeTasksJob.run(SynchronizeTasksJob.java:151)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeTasksJob.run(SynchronizeTasksJob.java:133)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

>com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.jetbrains.youtrack.javarest.utils.UserSavedSearches, and Java type class com.jetbrains.youtrack.javarest.utils.UserSavedSearches, and MIME media type application/xml; charset=UTF-8 was not found
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:550)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:506)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:684)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)
	at com.jetbrains.youtrack.javarest.client.YouTrackClient.getSavedSearchesForUser(YouTrackClient.java:513)
	at com.jetbrains.mylyn.yt.ui.YouTrackRepositoryQueryPage.fillSearches(YouTrackRepositoryQueryPage.java:375)
	at com.jetbrains.mylyn.yt.ui.YouTrackRepositoryQueryPage.createFastQueryCompositeContent(YouTrackRepositoryQueryPage.java:230)
	at com.jetbrains.mylyn.yt.ui.YouTrackRepositoryQueryPage.createPageContent(YouTrackRepositoryQueryPage.java:186)
	at com.jetbrains.mylyn.yt.ui.YouTrackRepositoryQueryPage.createControl(YouTrackRepositoryQueryPage.java:433)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:179)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:743)
	at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1183)
	at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1236)
	at org.eclipse.jface.wizard.WizardDialog.lambda$3(WizardDialog.java:1224)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1224)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:919)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:468)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4364)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4151)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3768)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.mylyn.internal.tasks.ui.actions.NewQueryAction.run(NewQueryAction.java:95)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4364)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4151)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3768)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

**Comment by VendettaPrime** [comment]
Have the same problem

**Comment by bvfalcon** [comment]
I solved this error in [my branch](https://github.com/bvfalcon/youtrack.mylyn.connector), but now actual [problem is in Eclipse UI](https://bugs.eclipse.org/bugs/show_bug.cgi?id=570704). Please vote for it too for quicker closing
